// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DtsMsg.proto

package com.ksyun.kbdp.dts.model.event.protobuf;

public final class DtsMsgWrapper {
  private DtsMsgWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DtsMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 jobInstId = 1;</code>
     * @return The jobInstId.
     */
    long getJobInstId();

    /**
     * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType type = 2;</code>
     * @return The type.
     */
    com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType getType();

    /**
     * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType executorType = 3;</code>
     * @return The enum numeric value on the wire for executorType.
     */
    int getExecutorTypeValue();
    /**
     * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType executorType = 3;</code>
     * @return The executorType.
     */
    com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType getExecutorType();

    /**
     * <code>string host = 4;</code>
     * @return The host.
     */
    java.lang.String getHost();
    /**
     * <code>string host = 4;</code>
     * @return The bytes for host.
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>int32 port = 5;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>string group = 6;</code>
     * @return The group.
     */
    java.lang.String getGroup();
    /**
     * <code>string group = 6;</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>string shardingInfo = 7;</code>
     * @return The shardingInfo.
     */
    java.lang.String getShardingInfo();
    /**
     * <code>string shardingInfo = 7;</code>
     * @return The bytes for shardingInfo.
     */
    com.google.protobuf.ByteString
        getShardingInfoBytes();
  }
  /**
   * Protobuf type {@code com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg}
   */
  public  static final class DtsMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg)
      DtsMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DtsMsg.newBuilder() to construct.
    private DtsMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DtsMsg() {
      type_ = 0;
      executorType_ = 0;
      host_ = "";
      group_ = "";
      shardingInfo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DtsMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DtsMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              jobInstId_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              executorType_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 40: {

              port_ = input.readInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              shardingInfo_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.class, com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PING = 0;</code>
       */
      PING(0),
      /**
       * <code>PONG = 1;</code>
       */
      PONG(1),
      /**
       * <code>ACK = 2;</code>
       */
      ACK(2),
      /**
       * <code>NACK = 3;</code>
       */
      NACK(3),
      /**
       * <code>JOB_REQUEST = 4;</code>
       */
      JOB_REQUEST(4),
      /**
       * <code>REGISTRY = 5;</code>
       */
      REGISTRY(5),
      /**
       * <code>REGISTRY_RESPONSE = 6;</code>
       */
      REGISTRY_RESPONSE(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PING = 0;</code>
       */
      public static final int PING_VALUE = 0;
      /**
       * <code>PONG = 1;</code>
       */
      public static final int PONG_VALUE = 1;
      /**
       * <code>ACK = 2;</code>
       */
      public static final int ACK_VALUE = 2;
      /**
       * <code>NACK = 3;</code>
       */
      public static final int NACK_VALUE = 3;
      /**
       * <code>JOB_REQUEST = 4;</code>
       */
      public static final int JOB_REQUEST_VALUE = 4;
      /**
       * <code>REGISTRY = 5;</code>
       */
      public static final int REGISTRY_VALUE = 5;
      /**
       * <code>REGISTRY_RESPONSE = 6;</code>
       */
      public static final int REGISTRY_RESPONSE_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CommandType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static CommandType forNumber(int value) {
        switch (value) {
          case 0: return PING;
          case 1: return PONG;
          case 2: return ACK;
          case 3: return NACK;
          case 4: return JOB_REQUEST;
          case 5: return REGISTRY;
          case 6: return REGISTRY_RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CommandType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CommandType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType)
    }

    /**
     * Protobuf enum {@code com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType}
     */
    public enum ExecutorType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>system = 0;</code>
       */
      system(0),
      /**
       * <code>tenant = 1;</code>
       */
      tenant(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>system = 0;</code>
       */
      public static final int system_VALUE = 0;
      /**
       * <code>tenant = 1;</code>
       */
      public static final int tenant_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ExecutorType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ExecutorType forNumber(int value) {
        switch (value) {
          case 0: return system;
          case 1: return tenant;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ExecutorType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ExecutorType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ExecutorType>() {
              public ExecutorType findValueByNumber(int number) {
                return ExecutorType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.getDescriptor().getEnumTypes().get(1);
      }

      private static final ExecutorType[] VALUES = values();

      public static ExecutorType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ExecutorType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType)
    }

    public static final int JOBINSTID_FIELD_NUMBER = 1;
    private long jobInstId_;
    /**
     * <code>int64 jobInstId = 1;</code>
     * @return The jobInstId.
     */
    public long getJobInstId() {
      return jobInstId_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType type = 2;</code>
     * @return The type.
     */
    public com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType getType() {
      @SuppressWarnings("deprecation")
      com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType result = com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType.valueOf(type_);
      return result == null ? com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType.UNRECOGNIZED : result;
    }

    public static final int EXECUTORTYPE_FIELD_NUMBER = 3;
    private int executorType_;
    /**
     * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType executorType = 3;</code>
     * @return The enum numeric value on the wire for executorType.
     */
    public int getExecutorTypeValue() {
      return executorType_;
    }
    /**
     * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType executorType = 3;</code>
     * @return The executorType.
     */
    public com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType getExecutorType() {
      @SuppressWarnings("deprecation")
      com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType result = com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType.valueOf(executorType_);
      return result == null ? com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType.UNRECOGNIZED : result;
    }

    public static final int HOST_FIELD_NUMBER = 4;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 4;</code>
     * @return The host.
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 4;</code>
     * @return The bytes for host.
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 5;
    private int port_;
    /**
     * <code>int32 port = 5;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }

    public static final int GROUP_FIELD_NUMBER = 6;
    private volatile java.lang.Object group_;
    /**
     * <code>string group = 6;</code>
     * @return The group.
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 6;</code>
     * @return The bytes for group.
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHARDINGINFO_FIELD_NUMBER = 7;
    private volatile java.lang.Object shardingInfo_;
    /**
     * <code>string shardingInfo = 7;</code>
     * @return The shardingInfo.
     */
    public java.lang.String getShardingInfo() {
      java.lang.Object ref = shardingInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shardingInfo_ = s;
        return s;
      }
    }
    /**
     * <code>string shardingInfo = 7;</code>
     * @return The bytes for shardingInfo.
     */
    public com.google.protobuf.ByteString
        getShardingInfoBytes() {
      java.lang.Object ref = shardingInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shardingInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (jobInstId_ != 0L) {
        output.writeInt64(1, jobInstId_);
      }
      if (type_ != com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType.PING.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (executorType_ != com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType.system.getNumber()) {
        output.writeEnum(3, executorType_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, host_);
      }
      if (port_ != 0) {
        output.writeInt32(5, port_);
      }
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, group_);
      }
      if (!getShardingInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, shardingInfo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (jobInstId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, jobInstId_);
      }
      if (type_ != com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType.PING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (executorType_ != com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType.system.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, executorType_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, port_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, group_);
      }
      if (!getShardingInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, shardingInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg)) {
        return super.equals(obj);
      }
      com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg other = (com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg) obj;

      if (getJobInstId()
          != other.getJobInstId()) return false;
      if (type_ != other.type_) return false;
      if (executorType_ != other.executorType_) return false;
      if (!getHost()
          .equals(other.getHost())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (!getShardingInfo()
          .equals(other.getShardingInfo())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JOBINSTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getJobInstId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + EXECUTORTYPE_FIELD_NUMBER;
      hash = (53 * hash) + executorType_;
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + SHARDINGINFO_FIELD_NUMBER;
      hash = (53 * hash) + getShardingInfo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg)
        com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.class, com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.Builder.class);
      }

      // Construct using com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jobInstId_ = 0L;

        type_ = 0;

        executorType_ = 0;

        host_ = "";

        port_ = 0;

        group_ = "";

        shardingInfo_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_descriptor;
      }

      @java.lang.Override
      public com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg getDefaultInstanceForType() {
        return com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg build() {
        com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg buildPartial() {
        com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg result = new com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg(this);
        result.jobInstId_ = jobInstId_;
        result.type_ = type_;
        result.executorType_ = executorType_;
        result.host_ = host_;
        result.port_ = port_;
        result.group_ = group_;
        result.shardingInfo_ = shardingInfo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg) {
          return mergeFrom((com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg other) {
        if (other == com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.getDefaultInstance()) return this;
        if (other.getJobInstId() != 0L) {
          setJobInstId(other.getJobInstId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.executorType_ != 0) {
          setExecutorTypeValue(other.getExecutorTypeValue());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (!other.getShardingInfo().isEmpty()) {
          shardingInfo_ = other.shardingInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long jobInstId_ ;
      /**
       * <code>int64 jobInstId = 1;</code>
       * @return The jobInstId.
       */
      public long getJobInstId() {
        return jobInstId_;
      }
      /**
       * <code>int64 jobInstId = 1;</code>
       * @param value The jobInstId to set.
       * @return This builder for chaining.
       */
      public Builder setJobInstId(long value) {
        
        jobInstId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 jobInstId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobInstId() {
        
        jobInstId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType type = 2;</code>
       * @return The type.
       */
      public com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType getType() {
        @SuppressWarnings("deprecation")
        com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType result = com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType.valueOf(type_);
        return result == null ? com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.CommandType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int executorType_ = 0;
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType executorType = 3;</code>
       * @return The enum numeric value on the wire for executorType.
       */
      public int getExecutorTypeValue() {
        return executorType_;
      }
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType executorType = 3;</code>
       * @param value The enum numeric value on the wire for executorType to set.
       * @return This builder for chaining.
       */
      public Builder setExecutorTypeValue(int value) {
        executorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType executorType = 3;</code>
       * @return The executorType.
       */
      public com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType getExecutorType() {
        @SuppressWarnings("deprecation")
        com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType result = com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType.valueOf(executorType_);
        return result == null ? com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType executorType = 3;</code>
       * @param value The executorType to set.
       * @return This builder for chaining.
       */
      public Builder setExecutorType(com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg.ExecutorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        executorType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg.ExecutorType executorType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecutorType() {
        
        executorType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 4;</code>
       * @return The host.
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 4;</code>
       * @return The bytes for host.
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 4;</code>
       * @param value The host to set.
       * @return This builder for chaining.
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 4;</code>
       * @param value The bytes for host to set.
       * @return This builder for chaining.
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 5;</code>
       * @return The port.
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 5;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>string group = 6;</code>
       * @return The group.
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group = 6;</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 6;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>string group = 6;</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shardingInfo_ = "";
      /**
       * <code>string shardingInfo = 7;</code>
       * @return The shardingInfo.
       */
      public java.lang.String getShardingInfo() {
        java.lang.Object ref = shardingInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shardingInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string shardingInfo = 7;</code>
       * @return The bytes for shardingInfo.
       */
      public com.google.protobuf.ByteString
          getShardingInfoBytes() {
        java.lang.Object ref = shardingInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shardingInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string shardingInfo = 7;</code>
       * @param value The shardingInfo to set.
       * @return This builder for chaining.
       */
      public Builder setShardingInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shardingInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string shardingInfo = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearShardingInfo() {
        
        shardingInfo_ = getDefaultInstance().getShardingInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string shardingInfo = 7;</code>
       * @param value The bytes for shardingInfo to set.
       * @return This builder for chaining.
       */
      public Builder setShardingInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shardingInfo_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg)
    }

    // @@protoc_insertion_point(class_scope:com.ksyun.kbdp.dts.model.event.protobuf.DtsMsg)
    private static final com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg();
    }

    public static com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DtsMsg>
        PARSER = new com.google.protobuf.AbstractParser<DtsMsg>() {
      @java.lang.Override
      public DtsMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DtsMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DtsMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DtsMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ksyun.kbdp.dts.model.event.protobuf.DtsMsgWrapper.DtsMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014DtsMsg.proto\022\'com.ksyun.kbdp.dts.model" +
      ".event.protobuf\"\217\003\n\006DtsMsg\022\021\n\tjobInstId\030" +
      "\001 \001(\003\022I\n\004type\030\002 \001(\0162;.com.ksyun.kbdp.dts" +
      ".model.event.protobuf.DtsMsg.CommandType" +
      "\022R\n\014executorType\030\003 \001(\0162<.com.ksyun.kbdp." +
      "dts.model.event.protobuf.DtsMsg.Executor" +
      "Type\022\014\n\004host\030\004 \001(\t\022\014\n\004port\030\005 \001(\005\022\r\n\005grou" +
      "p\030\006 \001(\t\022\024\n\014shardingInfo\030\007 \001(\t\"j\n\013Command" +
      "Type\022\010\n\004PING\020\000\022\010\n\004PONG\020\001\022\007\n\003ACK\020\002\022\010\n\004NAC" +
      "K\020\003\022\017\n\013JOB_REQUEST\020\004\022\014\n\010REGISTRY\020\005\022\025\n\021RE" +
      "GISTRY_RESPONSE\020\006\"&\n\014ExecutorType\022\n\n\006sys" +
      "tem\020\000\022\n\n\006tenant\020\001B\017B\rDtsMsgWrapperb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ksyun_kbdp_dts_model_event_protobuf_DtsMsg_descriptor,
        new java.lang.String[] { "JobInstId", "Type", "ExecutorType", "Host", "Port", "Group", "ShardingInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
