// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloModel.proto

package com.rolex.grpc.model;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rolex.grpc.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
