// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MallServerService.proto

package com.rolex.mall.service;

public final class MallService {
  private MallService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027MallServerService.proto\022\016com.rolex.mal" +
      "l\032\017MallModel.proto2N\n\014OrderService\022>\n\nli" +
      "stOrders\022\025.com.rolex.mall.Buyer\032\025.com.ro" +
      "lex.mall.Order\"\0000\0012Z\n\013CartService\022K\n\tadd" +
      "ToCart\022\034.com.rolex.mall.ProductOrder\032\034.c" +
      "om.rolex.mall.AddCartReply\"\000(\0012^\n\014StockS" +
      "ervice\022N\n\013batchDeduct\022\034.com.rolex.mall.P" +
      "roductOrder\032\033.com.rolex.mall.DeductReply" +
      "\"\000(\0010\001B\'\n\026com.rolex.mall.serviceB\013MallSe" +
      "rviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.rolex.mall.model.MallModel.getDescriptor(),
        });
    com.rolex.mall.model.MallModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
