// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MallModel.proto

package com.rolex.mall.model;

public interface BuyerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rolex.mall.Buyer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buyerId = 1;</code>
   * @return The buyerId.
   */
  int getBuyerId();
}
