// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MallModel.proto

package com.rolex.mall.model;

public final class MallModel {
  private MallModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rolex_mall_Buyer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rolex_mall_Buyer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rolex_mall_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rolex_mall_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rolex_mall_ProductOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rolex_mall_ProductOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rolex_mall_AddCartReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rolex_mall_AddCartReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rolex_mall_DeductReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rolex_mall_DeductReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MallModel.proto\022\016com.rolex.mall\"\030\n\005Buy" +
      "er\022\017\n\007buyerId\030\001 \001(\005\"S\n\005Order\022\017\n\007orderId\030" +
      "\001 \001(\005\022\021\n\tproductId\030\002 \001(\005\022\021\n\torderTime\030\003 " +
      "\001(\003\022\023\n\013buyerRemark\030\004 \001(\t\"1\n\014ProductOrder" +
      "\022\021\n\tproductId\030\001 \001(\005\022\016\n\006number\030\002 \001(\005\"-\n\014A" +
      "ddCartReply\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001" +
      "(\t\",\n\013DeductReply\022\014\n\004code\030\001 \001(\005\022\017\n\007messa" +
      "ge\030\002 \001(\tB#\n\024com.rolex.mall.modelB\tMallMo" +
      "delP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_rolex_mall_Buyer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rolex_mall_Buyer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rolex_mall_Buyer_descriptor,
        new java.lang.String[] { "BuyerId", });
    internal_static_com_rolex_mall_Order_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_rolex_mall_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rolex_mall_Order_descriptor,
        new java.lang.String[] { "OrderId", "ProductId", "OrderTime", "BuyerRemark", });
    internal_static_com_rolex_mall_ProductOrder_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_rolex_mall_ProductOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rolex_mall_ProductOrder_descriptor,
        new java.lang.String[] { "ProductId", "Number", });
    internal_static_com_rolex_mall_AddCartReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_rolex_mall_AddCartReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rolex_mall_AddCartReply_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_com_rolex_mall_DeductReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_rolex_mall_DeductReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rolex_mall_DeductReply_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
