// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloServerService.proto

package com.rolex.grpc.service;

public final class HelloServerService {
  private HelloServerService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030HelloServerService.proto\022\016com.rolex.gr" +
      "pc\032\020HelloModel.proto2W\n\014HelloService\022G\n\010" +
      "sayHello\022\034.com.rolex.grpc.HelloRequest\032\035" +
      ".com.rolex.grpc.HelloResponseB.\n\026com.rol" +
      "ex.grpc.serviceB\022HelloServerServiceP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.rolex.grpc.model.HelloModel.getDescriptor(),
        });
    com.rolex.grpc.model.HelloModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
