// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NameNodeRpcServer.proto

package com.rolex.dfs.rpc.service;

public final class NameNodeServer {
  private NameNodeServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027NameNodeRpcServer.proto\022\021com.rolex.dfs" +
      ".rpc\032\026NameNodeRpcModel.proto2\345\002\n\017NameNod" +
      "eService\022S\n\010register\022\".com.rolex.dfs.rpc" +
      ".RegisterRequest\032#.com.rolex.dfs.rpc.Reg" +
      "isterResponse\022V\n\theartbeat\022#.com.rolex.d" +
      "fs.rpc.HeartbeatRequest\032$.com.rolex.dfs." +
      "rpc.HeartbeatResponse\022Y\n\nunRegistry\022$.co" +
      "m.rolex.dfs.rpc.UnRegistryRequest\032%.com." +
      "rolex.dfs.rpc.UnRegistryResponse\022J\n\005mkdi" +
      "r\022\037.com.rolex.dfs.rpc.MkdirRequest\032 .com" +
      ".rolex.dfs.rpc.MkdirResponseB-\n\031com.role" +
      "x.dfs.rpc.serviceB\016NameNodeServerP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.rolex.dfs.rpc.model.NameNodeRpcModel.getDescriptor(),
        });
    com.rolex.dfs.rpc.model.NameNodeRpcModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
