spring:
  application:
    name: netty-client
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-wait: 1000s
        max-active: -1
        min-idle: 1
server:
  port: 8002

node:
  id: 2
  type: client
