// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProto.proto

package com.rolex.rpc.model.proto;

public final class MsgProtoWrapper {
  private MsgProtoWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rolex_grpc_MsgProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_rolex_grpc_MsgProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MsgProto.proto\022\016com.rolex.grpc\"\224\001\n\010Msg" +
      "Proto\022\r\n\005jobId\030\001 \001(\003\0222\n\004type\030\002 \001(\0162$.com" +
      ".rolex.grpc.MsgProto.CommandType\"E\n\013Comm" +
      "andType\022\010\n\004PING\020\000\022\010\n\004PONG\020\001\022\007\n\003ACK\020\002\022\010\n\004" +
      "NACK\020\003\022\017\n\013JOB_REQUEST\020\004B.\n\031com.rolex.rpc" +
      ".model.protoB\017MsgProtoWrapperP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_rolex_grpc_MsgProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_rolex_grpc_MsgProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_rolex_grpc_MsgProto_descriptor,
        new java.lang.String[] { "JobId", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
