// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProto.proto

package com.rolex.rpc.model.proto;

/**
 * Protobuf type {@code com.rolex.grpc.MsgProto}
 */
public  final class MsgProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.rolex.grpc.MsgProto)
    MsgProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MsgProto.newBuilder() to construct.
  private MsgProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MsgProto() {
    type_ = 0;
    executorType_ = 0;
    host_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MsgProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MsgProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            jobId_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            executorType_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            host_ = s;
            break;
          }
          case 40: {

            port_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.rolex.rpc.model.proto.MsgProtoWrapper.internal_static_com_rolex_grpc_MsgProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.rolex.rpc.model.proto.MsgProtoWrapper.internal_static_com_rolex_grpc_MsgProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.rolex.rpc.model.proto.MsgProto.class, com.rolex.rpc.model.proto.MsgProto.Builder.class);
  }

  /**
   * Protobuf enum {@code com.rolex.grpc.MsgProto.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PING = 0;</code>
     */
    PING(0),
    /**
     * <code>PONG = 1;</code>
     */
    PONG(1),
    /**
     * <code>ACK = 2;</code>
     */
    ACK(2),
    /**
     * <code>NACK = 3;</code>
     */
    NACK(3),
    /**
     * <code>JOB_REQUEST = 4;</code>
     */
    JOB_REQUEST(4),
    /**
     * <code>EXECUTOR_REGISTRY = 5;</code>
     */
    EXECUTOR_REGISTRY(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PING = 0;</code>
     */
    public static final int PING_VALUE = 0;
    /**
     * <code>PONG = 1;</code>
     */
    public static final int PONG_VALUE = 1;
    /**
     * <code>ACK = 2;</code>
     */
    public static final int ACK_VALUE = 2;
    /**
     * <code>NACK = 3;</code>
     */
    public static final int NACK_VALUE = 3;
    /**
     * <code>JOB_REQUEST = 4;</code>
     */
    public static final int JOB_REQUEST_VALUE = 4;
    /**
     * <code>EXECUTOR_REGISTRY = 5;</code>
     */
    public static final int EXECUTOR_REGISTRY_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return PING;
        case 1: return PONG;
        case 2: return ACK;
        case 3: return NACK;
        case 4: return JOB_REQUEST;
        case 5: return EXECUTOR_REGISTRY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rolex.rpc.model.proto.MsgProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.rolex.grpc.MsgProto.CommandType)
  }

  /**
   * Protobuf enum {@code com.rolex.grpc.MsgProto.ExecutorType}
   */
  public enum ExecutorType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>system = 0;</code>
     */
    system(0),
    /**
     * <code>tenant = 1;</code>
     */
    tenant(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>system = 0;</code>
     */
    public static final int system_VALUE = 0;
    /**
     * <code>tenant = 1;</code>
     */
    public static final int tenant_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ExecutorType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ExecutorType forNumber(int value) {
      switch (value) {
        case 0: return system;
        case 1: return tenant;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExecutorType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ExecutorType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExecutorType>() {
            public ExecutorType findValueByNumber(int number) {
              return ExecutorType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rolex.rpc.model.proto.MsgProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final ExecutorType[] VALUES = values();

    public static ExecutorType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ExecutorType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.rolex.grpc.MsgProto.ExecutorType)
  }

  public static final int JOBID_FIELD_NUMBER = 1;
  private long jobId_;
  /**
   * <code>int64 jobId = 1;</code>
   * @return The jobId.
   */
  public long getJobId() {
    return jobId_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <code>.com.rolex.grpc.MsgProto.CommandType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.rolex.grpc.MsgProto.CommandType type = 2;</code>
   * @return The type.
   */
  public com.rolex.rpc.model.proto.MsgProto.CommandType getType() {
    @SuppressWarnings("deprecation")
    com.rolex.rpc.model.proto.MsgProto.CommandType result = com.rolex.rpc.model.proto.MsgProto.CommandType.valueOf(type_);
    return result == null ? com.rolex.rpc.model.proto.MsgProto.CommandType.UNRECOGNIZED : result;
  }

  public static final int EXECUTORTYPE_FIELD_NUMBER = 3;
  private int executorType_;
  /**
   * <code>.com.rolex.grpc.MsgProto.ExecutorType executorType = 3;</code>
   * @return The enum numeric value on the wire for executorType.
   */
  public int getExecutorTypeValue() {
    return executorType_;
  }
  /**
   * <code>.com.rolex.grpc.MsgProto.ExecutorType executorType = 3;</code>
   * @return The executorType.
   */
  public com.rolex.rpc.model.proto.MsgProto.ExecutorType getExecutorType() {
    @SuppressWarnings("deprecation")
    com.rolex.rpc.model.proto.MsgProto.ExecutorType result = com.rolex.rpc.model.proto.MsgProto.ExecutorType.valueOf(executorType_);
    return result == null ? com.rolex.rpc.model.proto.MsgProto.ExecutorType.UNRECOGNIZED : result;
  }

  public static final int HOST_FIELD_NUMBER = 4;
  private volatile java.lang.Object host_;
  /**
   * <code>string host = 4;</code>
   * @return The host.
   */
  public java.lang.String getHost() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      host_ = s;
      return s;
    }
  }
  /**
   * <code>string host = 4;</code>
   * @return The bytes for host.
   */
  public com.google.protobuf.ByteString
      getHostBytes() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      host_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 5;
  private int port_;
  /**
   * <code>int32 port = 5;</code>
   * @return The port.
   */
  public int getPort() {
    return port_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (jobId_ != 0L) {
      output.writeInt64(1, jobId_);
    }
    if (type_ != com.rolex.rpc.model.proto.MsgProto.CommandType.PING.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (executorType_ != com.rolex.rpc.model.proto.MsgProto.ExecutorType.system.getNumber()) {
      output.writeEnum(3, executorType_);
    }
    if (!getHostBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, host_);
    }
    if (port_ != 0) {
      output.writeInt32(5, port_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (jobId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, jobId_);
    }
    if (type_ != com.rolex.rpc.model.proto.MsgProto.CommandType.PING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (executorType_ != com.rolex.rpc.model.proto.MsgProto.ExecutorType.system.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, executorType_);
    }
    if (!getHostBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, host_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, port_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.rolex.rpc.model.proto.MsgProto)) {
      return super.equals(obj);
    }
    com.rolex.rpc.model.proto.MsgProto other = (com.rolex.rpc.model.proto.MsgProto) obj;

    if (getJobId()
        != other.getJobId()) return false;
    if (type_ != other.type_) return false;
    if (executorType_ != other.executorType_) return false;
    if (!getHost()
        .equals(other.getHost())) return false;
    if (getPort()
        != other.getPort()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + JOBID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getJobId());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + EXECUTORTYPE_FIELD_NUMBER;
    hash = (53 * hash) + executorType_;
    hash = (37 * hash) + HOST_FIELD_NUMBER;
    hash = (53 * hash) + getHost().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.rolex.rpc.model.proto.MsgProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.rolex.rpc.model.proto.MsgProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.rolex.rpc.model.proto.MsgProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.rolex.grpc.MsgProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.rolex.grpc.MsgProto)
      com.rolex.rpc.model.proto.MsgProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rolex.rpc.model.proto.MsgProtoWrapper.internal_static_com_rolex_grpc_MsgProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rolex.rpc.model.proto.MsgProtoWrapper.internal_static_com_rolex_grpc_MsgProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rolex.rpc.model.proto.MsgProto.class, com.rolex.rpc.model.proto.MsgProto.Builder.class);
    }

    // Construct using com.rolex.rpc.model.proto.MsgProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      jobId_ = 0L;

      type_ = 0;

      executorType_ = 0;

      host_ = "";

      port_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.rolex.rpc.model.proto.MsgProtoWrapper.internal_static_com_rolex_grpc_MsgProto_descriptor;
    }

    @java.lang.Override
    public com.rolex.rpc.model.proto.MsgProto getDefaultInstanceForType() {
      return com.rolex.rpc.model.proto.MsgProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.rolex.rpc.model.proto.MsgProto build() {
      com.rolex.rpc.model.proto.MsgProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.rolex.rpc.model.proto.MsgProto buildPartial() {
      com.rolex.rpc.model.proto.MsgProto result = new com.rolex.rpc.model.proto.MsgProto(this);
      result.jobId_ = jobId_;
      result.type_ = type_;
      result.executorType_ = executorType_;
      result.host_ = host_;
      result.port_ = port_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.rolex.rpc.model.proto.MsgProto) {
        return mergeFrom((com.rolex.rpc.model.proto.MsgProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.rolex.rpc.model.proto.MsgProto other) {
      if (other == com.rolex.rpc.model.proto.MsgProto.getDefaultInstance()) return this;
      if (other.getJobId() != 0L) {
        setJobId(other.getJobId());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.executorType_ != 0) {
        setExecutorTypeValue(other.getExecutorTypeValue());
      }
      if (!other.getHost().isEmpty()) {
        host_ = other.host_;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.rolex.rpc.model.proto.MsgProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.rolex.rpc.model.proto.MsgProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long jobId_ ;
    /**
     * <code>int64 jobId = 1;</code>
     * @return The jobId.
     */
    public long getJobId() {
      return jobId_;
    }
    /**
     * <code>int64 jobId = 1;</code>
     * @param value The jobId to set.
     * @return This builder for chaining.
     */
    public Builder setJobId(long value) {
      
      jobId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 jobId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobId() {
      
      jobId_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.com.rolex.grpc.MsgProto.CommandType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.rolex.grpc.MsgProto.CommandType type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.rolex.grpc.MsgProto.CommandType type = 2;</code>
     * @return The type.
     */
    public com.rolex.rpc.model.proto.MsgProto.CommandType getType() {
      @SuppressWarnings("deprecation")
      com.rolex.rpc.model.proto.MsgProto.CommandType result = com.rolex.rpc.model.proto.MsgProto.CommandType.valueOf(type_);
      return result == null ? com.rolex.rpc.model.proto.MsgProto.CommandType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.rolex.grpc.MsgProto.CommandType type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.rolex.rpc.model.proto.MsgProto.CommandType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.rolex.grpc.MsgProto.CommandType type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int executorType_ = 0;
    /**
     * <code>.com.rolex.grpc.MsgProto.ExecutorType executorType = 3;</code>
     * @return The enum numeric value on the wire for executorType.
     */
    public int getExecutorTypeValue() {
      return executorType_;
    }
    /**
     * <code>.com.rolex.grpc.MsgProto.ExecutorType executorType = 3;</code>
     * @param value The enum numeric value on the wire for executorType to set.
     * @return This builder for chaining.
     */
    public Builder setExecutorTypeValue(int value) {
      executorType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.rolex.grpc.MsgProto.ExecutorType executorType = 3;</code>
     * @return The executorType.
     */
    public com.rolex.rpc.model.proto.MsgProto.ExecutorType getExecutorType() {
      @SuppressWarnings("deprecation")
      com.rolex.rpc.model.proto.MsgProto.ExecutorType result = com.rolex.rpc.model.proto.MsgProto.ExecutorType.valueOf(executorType_);
      return result == null ? com.rolex.rpc.model.proto.MsgProto.ExecutorType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.rolex.grpc.MsgProto.ExecutorType executorType = 3;</code>
     * @param value The executorType to set.
     * @return This builder for chaining.
     */
    public Builder setExecutorType(com.rolex.rpc.model.proto.MsgProto.ExecutorType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      executorType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.rolex.grpc.MsgProto.ExecutorType executorType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutorType() {
      
      executorType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object host_ = "";
    /**
     * <code>string host = 4;</code>
     * @return The host.
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string host = 4;</code>
     * @return The bytes for host.
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string host = 4;</code>
     * @param value The host to set.
     * @return This builder for chaining.
     */
    public Builder setHost(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      host_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string host = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHost() {
      
      host_ = getDefaultInstance().getHost();
      onChanged();
      return this;
    }
    /**
     * <code>string host = 4;</code>
     * @param value The bytes for host to set.
     * @return This builder for chaining.
     */
    public Builder setHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      host_ = value;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>int32 port = 5;</code>
     * @return The port.
     */
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 5;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(int value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {
      
      port_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.rolex.grpc.MsgProto)
  }

  // @@protoc_insertion_point(class_scope:com.rolex.grpc.MsgProto)
  private static final com.rolex.rpc.model.proto.MsgProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.rolex.rpc.model.proto.MsgProto();
  }

  public static com.rolex.rpc.model.proto.MsgProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MsgProto>
      PARSER = new com.google.protobuf.AbstractParser<MsgProto>() {
    @java.lang.Override
    public MsgProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MsgProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MsgProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MsgProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.rolex.rpc.model.proto.MsgProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

