// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProto.proto

package com.rolex.rpc.model.proto;

public interface MsgProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.rolex.grpc.MsgProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 jobId = 1;</code>
   * @return The jobId.
   */
  long getJobId();

  /**
   * <code>.com.rolex.grpc.MsgProto.CommandType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.rolex.grpc.MsgProto.CommandType type = 2;</code>
   * @return The type.
   */
  com.rolex.rpc.model.proto.MsgProto.CommandType getType();
}
